Tweak query syntax again for populating value on GH
neo4j-graph-examples/network-management pull request #10
Opened 2021-03-10 17:05 UTC by JMHReif

2021-03-10 17:17 UTC, fbiville commented on README.adoc
> +----
you might need a newline in there

2021-03-11 13:55 UTC, fbiville requested changes

2021-03-11 13:55 UTC, fbiville commented on README.adoc
> +[source,cypher,role=query-example-params]
```suggestion
[source,cypher,role=query-example-params,subs=+attributes]
```
as per Guillaume's suggestion

2021-03-15 18:39 UTC, JMHReif commented on README.adoc
> +[source,cypher,role=query-example-params]
Fixed! Thank you for the feedback!

2021-03-18 09:43 UTC, fbiville approved these changes

2021-03-18 09:44 UTC, fbiville commented
There seems to be conflicts, can you rebase your branch @JMHReif?

2021-04-28 15:56 UTC, merged